/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package staffetta_thread;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Davide
 */
public class Gara extends javax.swing.JFrame {

    Gestore gestore = new Gestore(0);
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Gara.class.getName());
    private Runner r1, r2, r3;

    /**
     * Creates new form Gara
     */
    public Gara() {
        initComponents();

        gestore = new Gestore(0);

        btn_avvia.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                btn_avvia.setEnabled(false);
                r1 = new Runner(1, gestore, prg_runner1, lbl_tempo1);
                r2 = new Runner(2, gestore, prg_runner2, lbl_tempo2);
                r3 = new Runner(3, gestore, prg_runner3, lbl_tempo3);
                r1.start();
                r2.start();
                r3.start();
                gestore.cambiaRunner(1);
            }
        });
    }

    private void farPartireGara() throws InterruptedException {

        btn_avvia.setEnabled(false);

        Runner r1 = new Runner(1, gestore, prg_runner1, lbl_tempo1);
        Runner r2 = new Runner(2, gestore, prg_runner2, lbl_tempo2);
        Runner r3 = new Runner(3, gestore, prg_runner3, lbl_tempo3);

        r1.start();
        r2.start();
        r3.start();

        gestore.cambiaRunner(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prg_runner2 = new javax.swing.JProgressBar();
        prg_runner1 = new javax.swing.JProgressBar();
        prg_runner3 = new javax.swing.JProgressBar();
        lbl_tempo1 = new javax.swing.JLabel();
        lbl_tempo2 = new javax.swing.JLabel();
        lbl_tempo3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_avvia = new javax.swing.JButton();
        btn_sospendi = new javax.swing.JButton();
        btn_riprende = new javax.swing.JButton();
        btn_slow = new javax.swing.JButton();
        btn_ferma = new javax.swing.JButton();
        btn_normal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(prg_runner2);
        prg_runner2.setBounds(40, 110, 490, 20);
        getContentPane().add(prg_runner1);
        prg_runner1.setBounds(40, 50, 490, 20);
        getContentPane().add(prg_runner3);
        prg_runner3.setBounds(40, 170, 490, 20);

        lbl_tempo1.setText("0");
        getContentPane().add(lbl_tempo1);
        lbl_tempo1.setBounds(630, 50, 60, 16);

        lbl_tempo2.setText("0");
        getContentPane().add(lbl_tempo2);
        lbl_tempo2.setBounds(630, 110, 60, 16);

        lbl_tempo3.setText("0");
        getContentPane().add(lbl_tempo3);
        lbl_tempo3.setBounds(630, 170, 60, 16);

        jLabel4.setText("Runner 1");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 30, 60, 16);

        jLabel5.setText("Runner 2");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 90, 50, 16);

        jLabel6.setText("Runner 3");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 150, 50, 16);

        btn_avvia.setText("Avvia");
        getContentPane().add(btn_avvia);
        btn_avvia.setBounds(50, 250, 75, 23);

        btn_sospendi.setText("Sospendi");
        btn_sospendi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sospendiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sospendi);
        btn_sospendi.setBounds(160, 250, 90, 23);

        btn_riprende.setText("Riprendi");
        btn_riprende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_riprendeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_riprende);
        btn_riprende.setBounds(280, 250, 74, 23);

        btn_slow.setText("Slow");
        btn_slow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_slowActionPerformed(evt);
            }
        });
        getContentPane().add(btn_slow);
        btn_slow.setBounds(390, 250, 72, 23);

        btn_ferma.setText("Stop");
        btn_ferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fermaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ferma);
        btn_ferma.setBounds(490, 250, 72, 23);

        btn_normal.setText("Normal");
        btn_normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_normalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_normal);
        btn_normal.setBounds(390, 290, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sospendiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sospendiActionPerformed
        if (r1 != null) {
            r1.setPausa(true);
            r2.setPausa(true);
            r3.setPausa(true);
        }
    }//GEN-LAST:event_btn_sospendiActionPerformed

    private void btn_riprendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_riprendeActionPerformed
        if (r1 != null) {
            r1.setPausa(false);
            r2.setPausa(false);
            r3.setPausa(false);
        }
    }//GEN-LAST:event_btn_riprendeActionPerformed

    private void btn_slowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_slowActionPerformed
        if (r1 != null) {
            r1.setVelocita(150);
            r2.setVelocita(150);
            r3.setVelocita(150);
        }
    }//GEN-LAST:event_btn_slowActionPerformed

    private void btn_fermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fermaActionPerformed
        if (r1 != null) {
            r1.fermaGara();
            r2.fermaGara();
            r3.fermaGara();
        }
        btn_avvia.setEnabled(true);
    }//GEN-LAST:event_btn_fermaActionPerformed

    private void btn_normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_normalActionPerformed
        if (r1 != null) {
            r1.setVelocita(50);
            r2.setVelocita(50);
            r3.setVelocita(50);
        }
    }//GEN-LAST:event_btn_normalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Gara().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_avvia;
    private javax.swing.JButton btn_ferma;
    private javax.swing.JButton btn_normal;
    private javax.swing.JButton btn_riprende;
    private javax.swing.JButton btn_slow;
    private javax.swing.JButton btn_sospendi;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_tempo1;
    private javax.swing.JLabel lbl_tempo2;
    private javax.swing.JLabel lbl_tempo3;
    private javax.swing.JProgressBar prg_runner1;
    private javax.swing.JProgressBar prg_runner2;
    private javax.swing.JProgressBar prg_runner3;
    // End of variables declaration//GEN-END:variables
}
